### ISSUE TITLE
selectTextStyle props cannot have Text styles

### ISSUE THREAD

**Issue by varunrayen** [peacechen/react-native-modal-selector#29] opened 2017-09-28 17:10 UTC
the `selectTextStyle` is supposed to inherit all the `Text` styles, but unfortunately when i use `fontSize` style it says it is invalid

**Comment by mikaello** [comment] 2017-09-29 06:17
This is duplicate of #25, fixed in PR #26 . Either use current master:

packages.json
```
...,
react-native-modal-selector: "peacechen/react-native-modal-selector",
...,
```

... or wait for `v0.0.20` to be released.

**Closed by mikaello** 2017-09-29 06:17 UTC

**Comment by peacechen** [comment] 2017-09-29 15:32
Published v0.0.20
